# Generated by Django 4.1.4 on 2022-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prodID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colour', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('available', models.BooleanField()),
                ('new', models.BooleanField()),
            ],
        ),
    ]
