# Generated by Django 4.1.4 on 2023-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0004_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
