# Generated by Django 4.1.4 on 2023-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('addressLine', models.CharField(max_length=500)),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('postalCode_zipCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
