# Generated by Django 4.1.4 on 2023-01-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0006_address_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
