# Generated by Django 4.1.4 on 2023-03-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0007_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchlist_referenceID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.customer')),
            ],
        ),
    ]
