# Generated by Django 4.1.4 on 2023-03-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0008_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='prodID',
            field=models.ForeignKey(db_column='prodID', on_delete=django.db.models.deletion.CASCADE, to='productDetails.product'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='userID',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='productDetails.customer'),
        ),
    ]
